- name: VS Marketplace Publisher
uses: MrLuje/vs-marketplace-publisher@v2
  with:
    # Token to access your github repository.
    github_token: # default is ${{ github.token }}
    # Personal access token to access your marketplace account.
    pat: 
    # Path to the extension manifest.
    manifestPath: 
    # Path to the extension package. Exclusive with useLatestReleaseAsset.
    vsixPath: # optional
    # Use the latest release from your repository that contains a vsix. Exclusive with vsixPath.
    useLatestReleaseAsset: # optional
          
